// <auto-generated />
using BicyclePartPicker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BicyclePartPicker.Migrations
{
    [DbContext(typeof(BicyclePartPickerContext))]
    [Migration("20240921172359_AddImage")]
    partial class AddImage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BicyclePartPicker.Models.Bicycle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Bicycle");
                });

            modelBuilder.Entity("BicyclePartPicker.Models.BicycleBottomBracket", b =>
                {
                    b.Property<int>("BicycleId")
                        .HasColumnType("int");

                    b.Property<int>("BottomBracketId")
                        .HasColumnType("int");

                    b.HasKey("BicycleId", "BottomBracketId");

                    b.HasIndex("BottomBracketId");

                    b.ToTable("BicycleBottomBracket");
                });

            modelBuilder.Entity("BicyclePartPicker.Models.BottomBracket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bBType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BottomBracket");
                });

            modelBuilder.Entity("BicyclePartPicker.Models.BicycleBottomBracket", b =>
                {
                    b.HasOne("BicyclePartPicker.Models.Bicycle", "Bicycle")
                        .WithMany("BicycleBottomBrackets")
                        .HasForeignKey("BicycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BicyclePartPicker.Models.BottomBracket", "BottomBracket")
                        .WithMany("BicycleBottomBrackets")
                        .HasForeignKey("BottomBracketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bicycle");

                    b.Navigation("BottomBracket");
                });

            modelBuilder.Entity("BicyclePartPicker.Models.Bicycle", b =>
                {
                    b.Navigation("BicycleBottomBrackets");
                });

            modelBuilder.Entity("BicyclePartPicker.Models.BottomBracket", b =>
                {
                    b.Navigation("BicycleBottomBrackets");
                });
#pragma warning restore 612, 618
        }
    }
}
